name: Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: env
        run: env
      - name: GitHub login
        run: |
          env
          echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_ACTOR" --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          IMAGE_DATE=$(date +%s)
          docker build --pull --tag docker.pkg.github.com/tomkins/ci-tox:$IMAGE_DATE .
          docker push docker.pkg.github.com/tomkins/ci-tox:$IMAGE_DATE
