name: Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: env
        run: env
      - name: Build Docker image
        run: |
          IMAGE_DATE=$(date +%s)
          docker build --pull --tag docker.pkg.github.com/tomkins/ci-tox:$IMAGE_DATE .
          docker push docker.pkg.github.com/tomkins/ci-tox:$IMAGE_DATE
